openapi: 3.0.0
info:
  title: My REST API
  version: 1.0.0
paths:
  /api/hello:
    get:
      summary: Returns a greeting message
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string